### ISSUE TITLE
[Feature] 🚀 Release Required

### ISSUE THREAD

**Issue by moha-b** [kokshibo/qwiker#1]
I would like to request a release of the current state of the repository. This will allow me to review and evaluate the work completed so far.

**Reason:**

Having a release will help in assessing the progress and the current state of the project, ensuring everything is on track.

Thank you!

[how to create a release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)

**Comment by kokshibo** [comment]
For now, I don't have time to address project issues and make a release. Feel free to fork it, download it, and fix it. Thank you for your interest.
